services:
  db:
    image: postgres:15
    container_name: weather_app_db
    restart: always
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather_network

  app:
    build: .
    container_name: weather_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://weather_user:weather_pass@db/weather_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - weather_network
    command: [ "/bin/sh", "-c", "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload" ]


volumes:
  postgres_data:

networks:
  weather_network:
